### ISSUE TITLE
mpi autodetection fails because b2 doesn't do as requested

### ISSUE THREAD

**Issue by iljah** [boostorg/mpi#80]
Trying to install boost mpi on a system where mpi compiler executable is called CC. For some reason adding `using mpi : CC ;` to tools/build/src/user-config.jam doesn't work and b2 says that mpi autodetection failed. If I instead add `using mpi : CC : <define>DAMNITB2JUSTUSECC ;` everything works. Naturally the added definition doesn't affect anything as far as C(++) code goes so why is it needed? Shouldn't b2 in both cases just use CC when compiling mpi code? Seems like a bug...

**Comment by aminiussi** [comment]
I suspect a documentation bug. We don't mention what to do when there is not wrapper.

-  `using mpi : CC ;` tell the build system to treat CC as a compiler wrapper and try to extract the compilation options, header, libs etc. in order to buld and MPI code with the C++ compiler (selected by the tool set).  It is used when the mpi wrapper does not have a "comon" name or is not in the default path but otherwise support usual detection options such as `-show`
- `using mpi : CC : <define>DAMNITB2JUSTUSECC ;` tell the build system that we do not rely on usual detection options (such as `-show`)  but explicitly provide compilation and link options. In that case 'CC' is not really used (not sure if it's optional), but we (well, you) still need to inhibit the other detection methods, which is achieved with dummy define option.

**Comment by aminiussi** [comment]
We need to at least mention that case in the documentation.  Not sure it's easy to fix through b2 (which wasn't very MPI friendly last time I checked). Probably better (less worse) to fix it through cmake at some point.

What platform is this ?
Thanks

**Comment by iljah** [comment]
Also note that CC can be any one of gcc, intel, cray compiler, depending on which module is loaded.

**Comment by aminiussi** [comment]
Documentation committed in master.
Nothing much we can do right now.
